[general]
live_config_reload = true
ipc_socket = true

[window]
decorations_theme_variant = "Dark"

[colors]
draw_bold_text_with_bright_colors = true

[font.normal]
family = "JetBrainsMono Nerd Font"

[cursor]
style = { shape = "Beam", blinking = "Always" }

[terminal]
osc52 = "CopyPaste"

[debug]
renderer = "glsl3"
prefer_egl = true
